[package]
name = "tinyalgo"
description = ""
version = "0.1.0"
license = "MIT"
authors = ["Daniel Lockyer <thisisdaniellockyer@gmail.com>"]
repository = "https://github.com/neosilky/tinyalgo"
homepage = "https://github.com/neosilky/tinyalgo"
categories = ["no-std"]
